<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class HospitalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('hospitals')->insertOrIgnore([
            
            // ================= AMMAN =================
            [
                'name_ar' => 'مستشفى الكندي',
                'name_en' => 'Al-Kindi Hospital',
                'slug' => Str::slug('Al Kindi Hospital'),
                'description_ar' => 'مستشفى خاص يقدم خدمات طبية متعددة التخصصات.',
                'description_en' => 'Private multi-specialty hospital.',
                'phone' => '065555001',
                'city_id' => 1,
                'address_ar' => 'عمان',
                'address_en' => 'Amman',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'المستشفى الإسلامي - العبدلي',
                'name_en' => 'Islamic Hospital - Abdali',
                'slug' => Str::slug('Islamic Hospital Abdali'),
                'description_ar' => 'مستشفى خاص يقدم خدمات طبية شاملة.',
                'description_en' => 'Private general hospital in Amman.',
                'phone' => '065555002',
                'city_id' => 1,
                'address_ar' => 'العبدلي - عمان',
                'address_en' => 'Abdali - Amman',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مدينة الحسين الطبية',
                'name_en' => 'King Hussein Medical City',
                'slug' => Str::slug('King Hussein Medical City'),
                'description_ar' => 'مجمع طبي عسكري متكامل تابع للخدمات الطبية الملكية.',
                'description_en' => 'Military medical complex.',
                'phone' => '065555003',
                'city_id' => 1,
                'address_ar' => 'عمان',
                'address_en' => 'Amman',
                'hospital_type_id' => 2,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى البشير',
                'name_en' => 'Al-Bashir Hospital',
                'slug' => Str::slug('Al Bashir Hospital'),
                'description_ar' => 'أكبر مستشفى حكومي في الأردن.',
                'description_en' => 'Largest government hospital in Jordan.',
                'phone' => '065555004',
                'city_id' => 1,
                'address_ar' => 'عمان',
                'address_en' => 'Amman',
                'hospital_type_id' => 1,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مركز الحسين للسرطان',
                'name_en' => 'King Hussein Cancer Center',
                'slug' => Str::slug('King Hussein Cancer Center'),
                'description_ar' => 'مركز متخصص لعلاج الأورام.',
                'description_en' => 'Specialized cancer treatment center.',
                'phone' => '065555005',
                'city_id' => 1,
                'address_ar' => 'عمان',
                'address_en' => 'Amman',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى دار السلام',
                'name_en' => 'Dar Al Salam Hospital',
                'slug' => Str::slug('Dar Al Salam Hospital'),
                'description_ar' => 'مستشفى خاص يقدم خدمات طبية عامة.',
                'description_en' => 'Private general hospital providing healthcare services.',
                'phone' => '065555006',
                'city_id' => 1,
                'address_ar' => 'عمان',
                'address_en' => 'Amman',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'المستشفى الأهلي',
                'name_en' => 'Al Ahli Hospital',
                'slug' => Str::slug('Al Ahli Hospital'),
                'description_ar' => 'مستشفى خاص متعدد التخصصات.',
                'description_en' => 'Multi-specialty private hospital.',
                'phone' => '065555007',
                'city_id' => 1,
                'address_ar' => 'عمان',
                'address_en' => 'Amman',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى الإسراء',
                'name_en' => 'Al Isra Hospital',
                'slug' => Str::slug('Al Isra Hospital'),
                'description_ar' => 'مستشفى خاص يقدم خدمات طبية متقدمة.',
                'description_en' => 'Advanced private medical services hospital.',
                'phone' => '065555008',
                'city_id' => 1,
                'address_ar' => 'عمان',
                'address_en' => 'Amman',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى الجامعة الأردنية',
                'name_en' => 'University of Jordan Hospital',
                'slug' => Str::slug('University of Jordan Hospital'),
                'description_ar' => 'مستشفى تعليمي تابع للجامعة الأردنية.',
                'description_en' => 'Teaching hospital of University of Jordan.',
                'phone' => '065555009',
                'city_id' => 1,
                'address_ar' => 'عمان',
                'address_en' => 'Amman',
                'hospital_type_id' => 3,
                'status' => 'approved',
                'user_id' => 1,
            ],
            // ================= IRBID =================
            [
                'name_ar' => 'مستشفى الملك المؤسس عبد الله الجامعي',
                'name_en' => 'King Abdullah University Hospital',
                'slug' => Str::slug('King Abdullah University Hospital'),
                'description_ar' => 'مستشفى جامعي تعليمي تابع لجامعة العلوم والتكنولوجيا.',
                'description_en' => 'Teaching university hospital.',
                'phone' => '027777001',
                'city_id' => 2,
                'address_ar' => 'إربد',
                'address_en' => 'Irbid',
                'hospital_type_id' => 3,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى إربد الإسلامي',
                'name_en' => 'Irbid Islamic Hospital',
                'slug' => Str::slug('Irbid Islamic Hospital'),
                'description_ar' => 'مستشفى خاص يقدم خدمات عامة.',
                'description_en' => 'Private general hospital.',
                'phone' => '027777002',
                'city_id' => 2,
                'address_ar' => 'إربد',
                'address_en' => 'Irbid',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى الرمثا',
                'name_en' => 'Al Ramtha Hospital',
                'slug' => Str::slug('Al Ramtha Hospital'),
                'description_ar' => 'مستشفى حكومي يخدم لواء الرمثا.',
                'description_en' => 'Government hospital serving Al Ramtha.',
                'phone' => '027777003',
                'city_id' => 2,
                'address_ar' => 'إربد',
                'address_en' => 'Irbid',
                'hospital_type_id' => 1,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى الأميرة بسمة',
                'name_en' => 'Princess Basma Hospital',
                'slug' => Str::slug('Princess Basma Hospital'),
                'description_ar' => 'مستشفى حكومي في محافظة إربد.',
                'description_en' => 'Government hospital in Irbid.',
                'phone' => '027777004',
                'city_id' => 2,
                'address_ar' => 'إربد',
                'address_en' => 'Irbid',
                'hospital_type_id' => 1,
                'status' => 'approved',
                'user_id' => 1,
            ],
            // ================= ZARQA =================
            [
                'name_ar' => 'مستشفى الزرقاء الحكومي الجديد',
                'name_en' => 'New Zarqa Government Hospital',
                'slug' => Str::slug('New Zarqa Government Hospital'),
                'description_ar' => 'مستشفى حكومي يخدم محافظة الزرقاء.',
                'description_en' => 'Government hospital serving Zarqa.',
                'phone' => '053333001',
                'city_id' => 3,
                'address_ar' => 'الزرقاء',
                'address_en' => 'Zarqa',
                'hospital_type_id' => 1,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى الزرقاء الوطني',
                'name_en' => 'Zarqa National Hospital',
                'slug' => Str::slug('Zarqa National Hospital'),
                'description_ar' => 'مستشفى خاص في الزرقاء.',
                'description_en' => 'Private hospital in Zarqa.',
                'phone' => '053333002',
                'city_id' => 3,
                'address_ar' => 'الزرقاء',
                'address_en' => 'Zarqa',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
            // ================= AQABA =================
            [
                'name_ar' => 'مستشفى العقبة الحديث',
                'name_en' => 'Aqaba Modern Hospital',
                'slug' => Str::slug('Aqaba Modern Hospital'),
                'description_ar' => 'مستشفى خاص في مدينة العقبة.',
                'description_en' => 'Private hospital in Aqaba.',
                'phone' => '032222001',
                'city_id' => 12,
                'address_ar' => 'العقبة',
                'address_en' => 'Aqaba',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],

            [
                'name_ar' => 'مستشفى السلط الحكومي',
                'name_en' => 'Salt Government Hospital',
                'slug' => Str::slug('Salt Government Hospital'),
                'description_ar' => 'مستشفى حكومي رئيسي في البلقاء.',
                'description_en' => 'Main government hospital in Balqa.',
                'phone' => '055555001',
                'city_id' => 4,
                'address_ar' => 'السلط',
                'address_en' => 'Salt',
                'hospital_type_id' => 1,
                'status' => 'approved',
                'user_id' => 1,
            ],

            [
                'name_ar' => 'مستشفى الكرك الحكومي',
                'name_en' => 'Karak Government Hospital',
                'slug' => Str::slug('Karak Government Hospital'),
                'description_ar' => 'مستشفى حكومي في محافظة الكرك.',
                'description_en' => 'Government hospital in Karak.',
                'phone' => '032222002',
                'city_id' => 5,
                'address_ar' => 'الكرك',
                'address_en' => 'Karak',
                'hospital_type_id' => 1,
                'status' => 'approved',
                'user_id' => 1,
            ],
            [
                'name_ar' => 'مستشفى العقبة الإسلامي',
                'name_en' => 'Aqaba Islamic Hospital',
                'slug' => Str::slug('Aqaba Islamic Hospital'),
                'description_ar' => 'مستشفى خاص في العقبة.',
                'description_en' => 'Private hospital in Aqaba.',
                'phone' => '032222003',
                'city_id' => 12,
                'address_ar' => 'العقبة',
                'address_en' => 'Aqaba',
                'hospital_type_id' => 5,
                'status' => 'approved',
                'user_id' => 1,
            ],
        ]);
    }    
}
